name: Hello Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Replace with the desired Python version (e.g., 3.9)
        
    - name: Check out code
      uses: actions/checkout@v2
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run Python script
      run: python hello.py